item_name = input('Enter food item name: \n')
item_price = float(input('Enter item price: \n'))
item_quantity = int(input('Enter item quantity: \n'))
total_cost = (item_price * item_quantity)
print ('')
print ('RECEIPT')
print (item_quantity, item_name, '@ $', item_price, '= $', total_cost)
print ('Total cost: $', total_cost)

print ('')
print ('')
item2_name = input('Enter second food item name: \n')
item2_price = float(input('Enter item price: \n'))
item2_quantity = int(input('Enter item quantity: \n'))
total_cost2 = (item2_price * item2_quantity)
print ('')
print ('RECEIPT')
print (item_quantity, item_name, '@ $', item_price, '= $', total_cost)
print (item2_quantity, item2_name, '@ $', item2_price, '= $', total_cost2)
grand_total = (total_cost2 + total_cost)
print ('Total cost: $', grand_total)
print ('')
gratuity = (grand_total * 0.15)
print ('15% gratuity: $', gratuity)
print ('Total with tip: $', (grand_total + gratuity))
